[gcp_service_account]
type = "service_account"
project_id = "solid-solstice-491215-k0"
private_key_id = "1b117dd5a16d9b91ea51e6ab6f799ea6a10e6ce2"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDlo+u0wtJxpy5E
bWFe/RNpQE2ZNZlsIY70zquL6ElQo3hVlzwsawQnQM4gAg41w56z8K1TxhXzfBz1
FOM0S9oN/RjohWhnuypr1X0a03OsmWqmzuXVUlcosmc6dkcSk7L3Aqq1yPqPWarU
HpQY5CltGRrdI6zhNOu6suPP0Wm+enSn6PC2qBN5iCa+frFZKR2B5fLyKERCC4wu
k4rGwqkFRziyfEaHeqSYRkPJAr1C3KblUIDEg79WCgEDUhSvPNNhF3t9QP9fIiHy
EhJt2rvSCNhCs0ExfXus7hfbLPRUbcc7DNnCdYt56ZI06KdoEXINwxtzg3Hkj3YM
A2Jz1GuvAgMBAAECggEAMDb6hjlhdftj+3n7t7XrHW4i3MgkLk/ddAjwe6+JtSSd
X1shhzHw7Uzt+kp0MVWhPKaLvcsZUMX+TnbUPWavocBCOo/IG/9wKLPqUHeVEegk
PGG0X9Wp9yF+CwhKY9we9z3YGdLYyMBK3b6N2awOBpn+ye9znNU/qTNmIXwWd6dY
ZjMZh9XnhpmhFMxY+6Uv4joZ+eDTKkWd1u893vBjzbRIpcsd24GVMbNcC3swhqe2
iOSn76WJkY+d2hzip3LXyBt8NaYuYR6oPTJ+RFg0D035/Q7ejPz6/4y5PwBDFrrC
p3io2FglLkYc8TaSabyhWiIKIH2nJilmWZzLTpjYAQKBgQD+yFcdP5KbKs7fTZr6
/4tlZJBBghBk2i6aM5uqd9mVmLqO/rRuqxymuhuAUIeQsZG1hqq4S1sgDenTgR4j
sl4xbBIcOITLfLrc6oVajce3U4OnSyIktcwlyTHYWFA+bHq+cONeMntkerXxvxQF
rQPlSuvNy5XBggJEJxPMd7My3wKBgQDmvNNRxfpkud1z0t9J2Q4GkA0hlkrUe6TU
31a+tHMlUefuRw83lrjE83DCTS8LMZYCU2zpb2Hm46N2jjUxNG64rKAVIF/ZQWqq
6Uju0V4sPi9JxDO5IxGiKKbzFqEjBcG+VF7CsBuJtJKsh1P4DO5iqcX1f0zNfHBi
qCbcnpUxMQKBgCY2G8KaNz2oVPBurjC4xMpHI89/V0AY7OZZmR4e7XYfOtOZZaw3
Y4up29gJu9s6lnTYJqCPRLJxA8Gh2shVxwS4hZrP6zKtmUTqs2daXjqjftpHTW6e
CWkdXKlqzVYfZOVM/vywq4rtUH5aPwF+6leoPedWgjZMblSUW8bNqQWXAoGAS+nw
NMVIPn+QRp0obamGHc6jI1vJPuN3NbpNVe0UvUCXaCPk88sY+2OEw8iVI7+qtRUx
jhPhSA+5JjZfddLkYsoY2RqPrnEBYT3jiv9DVpcXA9QTmGPbV1i8pNnbJiSsu6wS
iUdbqBDK+QyFKeVHQRrOUJkTcb/xUeQ09P0P5OECgYBc0d/BO4kMqAObENxsq4YN
8VY6hickOto6sI5XRe/9gXsrcQQzRkKmMKSmxtRCz0l+bsVFkE4V5BKaNn532OTW
rW3Gcr+J+VtqidAI6XjycQHDXSmbUZIef0CqrGQCQLyjUEDDSSOdiqhG3aLVFCNn
9snJLAMHJwOHdxbizHbMfw==
-----END PRIVATE KEY-----
"""
client_email = "streamlit-easter-app@solid-solstice-491215-k0.iam.gserviceaccount.com"
client_id = "108213715668562048608"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-easter-app%40solid-solstice-491215-k0.iam.gserviceaccount.com"
